spring.application.name=portfolio-manager
spring.datasource.url=jdbc:h2:file:./data/portfolio-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

finnhub.api.key=d6utqi1r01qig545sf7gd6utqi1r01qig545sf80